### ISSUE TITLE
Discrepancy Between Summary View and Yearly Commit Views

### ISSUE THREAD

**Issue by onlydole** [cncf/devstats#50] opened 2024-01-24 23:19 UTC
From this summary view, it shows Intuit as having 3595 total commits.
> https://all.devstats.cncf.io/d/5/companies-table?orgId=1&var-period_name=Last%20year&var-metric=commits

When I look at the previous year’s commits via this view, then I am only able to export 1112 commits via the inspect view to CSV.
> https://all.devstats.cncf.io/d/56/company-commits-table?orgId=1&from=now-1y/y&to=now-1y/y&var-repogroups=All&var-companies=Intuit%20Inc.

**Comment by lukaszgryglicki** [comment] 2024-01-24 23:40
Hi, will TAL after my PTO.

**Comment by lukaszgryglicki** [comment] 2024-01-29 05:01
So the problem is that the 1st dashboard considers all commits where given company is author or committer or pusher, see: https://github.com/cncf/devstats/blob/master/metrics/shared/project_company_stats.sql
1) Author: https://github.com/cncf/devstats/blob/master/metrics/shared/project_company_stats.sql#L16
2) Committer: https://github.com/cncf/devstats/blob/master/metrics/shared/project_company_stats.sql#L30
3) Actor/Pusher: https://github.com/cncf/devstats/blob/master/metrics/shared/project_company_stats.sql#L3

While the detailed view only considers authors:
Authors: https://github.com/cncf/devstats/blob/master/metrics/shared/company_commits_data.sql#L9

I will update metric to consider all 3 possible commit contributors and see if that helps.
Additionally 1st dashboard is not checking if repo group is defined for a given contrribution while the latter does.

Will update once I check this.

**Comment by lukaszgryglicki** [comment] 2024-01-29 05:30
I've updated the SQL in 2nd dashboard to consider `authors`, `committers` and `actors` and now I'm regenerating data.

**Comment by lukaszgryglicki** [comment] 2024-01-29 05:39
I've regenerated data and now I'm able to get 2703 commits - this is a lot closer than it was - now the difference (a lot smaller) is probably due to already mentioned repo groups additional condition + 1st dashboard uses approx count (using hyper log log - HLL) - also it was generated at different point in time (the 2nd is regenerated now), I['m closing this - please reopen if anything more is needed there, but I *think* is is good enough now.

**Comment by lukaszgryglicki** [comment] 2024-01-29 05:40
https://all.devstats.cncf.io/d/56/company-commits-table?orgId=1&from=now-1y&to=now&var-repogroups=All&var-companies=Intuit%20Inc.&viewPanel=1

**Closed as completed by lukaszgryglicki** 2024-01-29 05:39 UTC
Labels: bug, help wanted
